-- Homeschool Tracker
-- Migration 010: Progress dashboard + permanent official report snapshots
--
-- Live progress is calculated by the application from permanent academic records.
-- This migration adds integrity protection and a staff-only RPC that freezes the
-- exact calculated data into report_snapshots.

begin;

alter table public.report_snapshots
  add column if not exists snapshot_sha256 text;

create unique index if not exists report_snapshots_student_version_uq
  on public.report_snapshots (student_id, version);

-- Official reports are historical records. Their payload cannot be edited or
-- deleted. A later workflow may void an official report, but voiding preserves
-- the exact original snapshot.
create or replace function private.protect_report_snapshot_history()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    if old.status in ('official', 'voided') then
      raise exception 'Official or voided report snapshots cannot be deleted';
    end if;
    return old;
  end if;

  if old.status = 'official' then
    if new.status = 'voided'
       and (to_jsonb(new) - 'status') = (to_jsonb(old) - 'status') then
      return new;
    end if;

    raise exception 'Official report snapshots are immutable';
  end if;

  if old.status = 'voided' then
    raise exception 'Voided report snapshots are immutable';
  end if;

  return new;
end;
$$;

drop trigger if exists protect_report_snapshot_history on public.report_snapshots;
create trigger protect_report_snapshot_history
  before update or delete on public.report_snapshots
  for each row execute function private.protect_report_snapshot_history();

create or replace function public.create_official_progress_report(
  p_student_id uuid,
  p_academic_year_id uuid,
  p_report_type text,
  p_period_start date,
  p_period_end date,
  p_snapshot_data jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_organization_id uuid;
  v_version integer;
  v_report_id uuid;
  v_hash text;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  if p_period_start is null or p_period_end is null or p_period_end < p_period_start then
    raise exception 'A valid reporting period is required.' using errcode = '22023';
  end if;

  if p_report_type not in (
    'progress_report',
    'quarter_report',
    'semester_report',
    'annual_report',
    'attendance_report',
    'competency_report'
  ) then
    raise exception 'Invalid report type.' using errcode = '22023';
  end if;

  if p_snapshot_data is null or jsonb_typeof(p_snapshot_data) <> 'object' then
    raise exception 'Report snapshot data must be a JSON object.' using errcode = '22023';
  end if;

  select s.organization_id
  into v_organization_id
  from public.students s
  where s.id = p_student_id;

  if not found then
    raise exception 'Student was not found.' using errcode = '22023';
  end if;

  if not private.is_org_staff(v_organization_id) then
    raise exception 'Instructor access is required.' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.student_academic_years say
    where say.organization_id = v_organization_id
      and say.student_id = p_student_id
      and say.academic_year_id = p_academic_year_id
  ) then
    raise exception 'Academic year placement was not found for this student.'
      using errcode = '22023';
  end if;

  -- Guard against accidentally freezing a snapshot for a different student or org.
  if coalesce(p_snapshot_data #>> '{student,id}', '') <> p_student_id::text
     or coalesce(p_snapshot_data #>> '{organization,id}', '') <> v_organization_id::text
     or coalesce(p_snapshot_data #>> '{academic_year,id}', '') <> p_academic_year_id::text then
    raise exception 'Snapshot identity does not match the requested student record.'
      using errcode = '22023';
  end if;

  select coalesce(max(r.version), 0) + 1
  into v_version
  from public.report_snapshots r
  where r.student_id = p_student_id;

  v_hash := encode(public.digest(p_snapshot_data::text, 'sha256'), 'hex');

  perform set_config('app.audit_reason', 'Official progress report generated by instructor', true);

  insert into public.report_snapshots (
    organization_id,
    student_id,
    academic_year_id,
    version,
    report_type,
    status,
    period_start,
    period_end,
    snapshot_data,
    snapshot_sha256,
    generated_by,
    generated_at
  )
  values (
    v_organization_id,
    p_student_id,
    p_academic_year_id,
    v_version,
    p_report_type,
    'official',
    p_period_start,
    p_period_end,
    p_snapshot_data,
    v_hash,
    v_user_id,
    now()
  )
  returning id into v_report_id;

  return v_report_id;
end;
$$;

revoke all on function public.create_official_progress_report(
  uuid, uuid, text, date, date, jsonb
) from public;

grant execute on function public.create_official_progress_report(
  uuid, uuid, text, date, date, jsonb
) to authenticated;

commit;
